version: '3.8'

services:
  nginx: 
    image: nginx:latest
    container_name: rbt_nginx
    volumes:
      - ./SmartYard-Server:/var/www/html                          # RBT dir
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/    # Nginx config
    ports:
    - "8876:80"                                      # RBT HTTP port
    - "443:9091"                                     # RBT HTTPS port
    depends_on:
      - app
      - redis
      - clickhouse_server
      - postgres
      - mongo
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_NGINX_NETWORK_ADDRESS}"

  app:
    container_name: rbt_app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./SmartYard-Server/:/var/www/html
      - rbt_app:/var/spool/cron/crontabs
    depends_on:
      - redis  
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_APP_NETWORK_ADDRESS}"

  redis:
    container_name: rbt_db_redis
    image: redis:7-alpine
    command: ["sh", "-c", "exec redis-server --requirepass \"${RBT_REDIS_PASSWORD}\""]
    ports:
      - "6379"
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_REDIS_NETWORK_ADDRESS}"

  mongo:
    container_name: rbt_db_mongo
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${RBT_MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${RBT_MONGO_PASSWORD}"
    volumes:
      - db_mongodb:/data/db
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_MONGO_NETWORK_ADDRESS}"

  postgres:
    container_name: rbt_db_postgres
    image: postgres:15.1
    environment:
      POSTGRES_DB: "rbt"
      POSTGRES_USER: "rbt"
      POSTGRES_PASSWORD: "rbt"
    ports:
      - "5432"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_POSTGRESS_NETWORK_ADDRESS}"

  clickhouse_server:
    container_name: rbt_db_clickhouse
    image: clickhouse/clickhouse-server
    ports:
     - "8123"
     - "9004"
    volumes:
     - db_clickhouse:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: "${RBT_CLICKHOUSE_DB}"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_USER: "${RBT_CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${RBT_CLICKHOUSE_PASSWORD}"
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_CLICKHOUSE_NETWORK_ADDRESS}"

  asterisk:
    container_name: rbt_asterisk
    build:
      context: .
      dockerfile: docker/asterisk/Dockerfile
    volumes:
      - ./SmartYard-Server/install/asterisk:/etc/asterisk
    depends_on:
      - nginx
    network_mode: host
    ## SIP UDP port 5060
    ## SIP TCP port 5060
    ## WS port 8088
    ## RTP ports 10000-20000

  syslog:
    container_name: rbt_syslog
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./SmartYard-Server/server/syslog:/home/node/app
    depends_on:
      - nginx
    ports:
      - "${RBT_SYSLOG_PORT_BEWARD}:${RBT_SYSLOG_PORT_BEWARD}/udp"
      - "${RBT_SYSLOG_PORT_BEWARD_DS}:${RBT_SYSLOG_PORT_BEWARD_DS}/udp"
      - "${RBT_SYSLOG_PORT_QTECH}:${RBT_SYSLOG_PORT_QTECH}/udp"
      - "${RBT_SYSLOG_PORT_IS}:${RBT_SYSLOG_PORT_IS}/udp"
      - "${RBT_SYSLOG_PORT_AKUVOX}:${RBT_SYSLOG_PORT_AKUVOX}/udp"
    command: npm run start
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_SYSLOG_NETWORK_ADDRESS}"

  mosquitto:
    image: eclipse-mosquitto
    container_name: rbt_mqtt
    #TODO: add configs
    #volumes:
    ports:
      - 1883:1883
      - 8081:8081
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_MOSQUITTO_NETWORK_ADDRESS}"

volumes:
  db_postgres:
  db_clickhouse:
  db_mongodb:
  rbt_app:

networks:
  rbt-app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${RBT_NETWORK_ADDRESS}"
          gateway: "${RBT_NETWORK_GW}"
