services:
  nginx:
    image: nginx:latest
    container_name: "rbt_nginx_${RBT_INSTANCE}"
    volumes:
      - ./SmartYard-Server:/var/www/html              # RBT dir
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/     # Nginx config
    ports:
      - "${RBT_NGINX_PORT_WEB}:80"                    # RBT HTTP port
      - "${RBT_NGINX_PORT_SSL}:443"                   # RBT HTTPS port
    depends_on:
      - app
    networks:
      default:
        ipv4_address: "${RBT_NGINX_NETWORK_ADDRESS}"
      shared-network-dev:

  app:
    container_name: "rbt_app_${RBT_INSTANCE}"
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - ./SmartYard-Server/:/var/www/html
      - rbt_app:/var/spool/cron/crontabs
    depends_on:
      - redis
      - clickhouse_server
      - postgres
      - mongo
    networks:
      default:
        ipv4_address: "${RBT_APP_NETWORK_ADDRESS}"

  redis:
    container_name: "rbt_db_redis_${RBT_INSTANCE}"
    image: redis:7-alpine
    command: ["sh", "-c", "exec redis-server --requirepass \"${RBT_REDIS_PASSWORD}\""]
    ports:
      - "${RBT_REDIS_PORT}"
    networks:
      default:
        ipv4_address: "${RBT_REDIS_NETWORK_ADDRESS}"

  mongo:
    container_name: "rbt_db_mongo_${RBT_INSTANCE}"
    image: mongo:latest
    ports:
      - "${RBT_MONGO_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${RBT_MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${RBT_MONGO_PASSWORD}"
    volumes:
      - db_mongodb:/data/db
    networks:
      default:
        ipv4_address: "${RBT_MONGO_NETWORK_ADDRESS}"

  postgres:
    container_name: "rbt_db_postgres_${RBT_INSTANCE}"
    image: "postgres:${RBT_POSTGRES_PORT_VERSION}"
    environment:
      POSTGRES_DB: "${RBT_POSTGRES_DB}"
      POSTGRES_USER: "${RBT_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${RBT_POSTGRES_PASSWORD}"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "${RBT_POSTGRES_PORT}"
    volumes:
      - db_postgres:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: "${RBT_POSTGRES_NETWORK_ADDRESS}"

  clickhouse_server:
    container_name: "rbt_db_clickhouse_${RBT_INSTANCE}"
    image: clickhouse/clickhouse-server
    ports:
      - "8123"
      - "9004"
    volumes:
      - db_clickhouse:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: "${RBT_CLICKHOUSE_DB}"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_USER: "${RBT_CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${RBT_CLICKHOUSE_PASSWORD}"
    networks:
      default:
        ipv4_address: "${RBT_CLICKHOUSE_NETWORK_ADDRESS}"

  asterisk:
    container_name: "rbt_asterisk_${RBT_INSTANCE}"
    build:
      context: .
      dockerfile: docker/asterisk/Dockerfile
    volumes:
      - ./SmartYard-Server/asterisk:/etc/asterisk
    depends_on:
      - nginx
    network_mode: host

  event:
    container_name: "rbt_event_${RBT_INSTANCE}"
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: event_main
    volumes:
      - ./SmartYard-Server/server/services/event/config.json:/home/node/app/config.json
    depends_on:
      - nginx
    ports:
      - "${RBT_EVENT_SERVER_PORT_BEWARD}:${RBT_EVENT_SERVER_PORT_BEWARD}/udp"
      - "${RBT_EVENT_SERVER_PORT_BEWARD_DS}:${RBT_EVENT_SERVER_PORT_BEWARD_DS}/udp"
      - "${RBT_EVENT_SERVER_PORT_QTECH}:${RBT_EVENT_SERVER_PORT_QTECH}/udp"
      - "${RBT_EVENT_SERVER_PORT_IS}:${RBT_EVENT_SERVER_PORT_IS}/udp"
      - "${RBT_EVENT_SERVER_PORT_AKUVOX}:${RBT_EVENT_SERVER_PORT_AKUVOX}/udp"
      - "${RBT_EVENT_SERVER_PORT_SPUTNIK_CLOUD}:${RBT_EVENT_SERVER_PORT_SPUTNIK_CLOUD}/udp"
    command: npm run start
    networks:
      default:
        ipv4_address: "${RBT_EVENT_SERVER_NETWORK_ADDRESS}"

  push:
    container_name: "rbt_push_${RBT_INSTANCE}"
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      target: push_main
    volumes:
      - ./SmartYard-Server/server/services/push/assets/:/home/node/app/assets/
      - ./SmartYard-Server/server/services/push/.env:/home/node/app/.env
    depends_on:
      - nginx
    ports:
      - "${RBT_PUSH_SERVICE_PORT}:${RBT_PUSH_SERVICE_PORT}/tcp"
    command: npm run start
    networks:
      default:
        ipv4_address: "${RBT_PUSH_SERVICE_NETWORK_ADDRESS}"

  mosquitto:
    image: eclipse-mosquitto
    container_name: "rbt_mqtt_${RBT_INSTANCE}"
    #TODO: add configs
    #volumes:
    ports:
      - "${RBT_MOSQUITTO_PORT}:1883"
      - "${RBT_MOSQUITTO_PORT_WS}:8081"
    networks:
      default:
        ipv4_address: "${RBT_MOSQUITTO_NETWORK_ADDRESS}"

  kamailio:
    profiles:
      - sbc
    container_name: "rbt_kamailio_${RBT_INSTANCE}"
    build:
      context: .
      dockerfile: docker/kamailio/Dockerfile
    network_mode: host
    volumes:
      - ./SmartYard-Server/install/kamailio/:/etc/kamailio
    depends_on:
      - app
      - rtpengine

  kamailio_dev:
    profiles:
      - sbc
    container_name: "rbt_kamailio_dev_${RBT_INSTANCE}"
    build:
      context: .
      dockerfile: docker/kamailio/Dockerfile_dev
    network_mode: host
    volumes:
      - ./docker/kamailio/dev/v4/:/etc/kamailio
    depends_on:
      - app
      - rtpengine

  rtpengine:
    profiles:
      - sbc
    container_name: "rbt_rtpengine_${RBT_INSTANCE}"
    image: fonoster/rtpengine:latest
    network_mode: host
    volumes:
      - ./SmartYard-Server/install/rtpengine/rtpengine.conf:/etc/rtpengine/rtpengine.conf
    command: rtpengine --config-file=/etc/rtpengine/rtpengine.conf --foreground

volumes:
  db_postgres:
  db_clickhouse:
  db_mongodb:
  rbt_app:

networks:
  default:
    name: "rbt_stack_${RBT_INSTANCE}"
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${RBT_NETWORK_ADDRESS}"
          gateway: "${RBT_NETWORK_GW}"

  shared-network-dev:
    external: true