version: '3.9'

services:
  nginx: 
    image: nginx:latest
    container_name: rbt_nginx
    volumes:
      - ./rbt:/var/www/html                           # RBT dir
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/    # Nginx config
#LOGS optional
#      - ./_docker/log/nginx/:/var/log/nginx
    ports:
    - "8876:80"                                       # RBT HTTP port
    - "9091:9091"                                     # RBT HTTPS port
    depends_on:
      - app
      - redis
      - clickhouse_server
      - postgres
      - mongo
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_NGINX_NETWORK_ADDRESS}"

  app:
    container_name: rbt_app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./rbt/:/var/www/html
    depends_on:
      - redis  
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_APP_NETWORK_ADDRESS}"

  redis:
    container_name: rbt_db_redis
    image: redis:7-alpine
    command: ["sh", "-c", "exec redis-server --requirepass \"${RBT_REDIS_PASSWORD}\""]
    ports:
      - "6379"
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_REDIS_NETWORK_ADDRESS}"

  mongo:
    container_name: rbt_db_mongo
    image: mongo:latest
    ports:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${RBT_MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${RBT_MONGO_PASSWORD}"
    volumes:
      - mongodata:/data/db
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_MONGO_NETWORK_ADDRESS}"

  postgres:
    container_name: rbt_db_postgress
    image: postgres:15.1
    environment:
      POSTGRES_DB: "rbt"
      POSTGRES_USER: "rbt"
      POSTGRES_PASSWORD: "rbt"
    ports:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_POSTGRESS_NETWORK_ADDRESS}"

  clickhouse_server:
    container_name: rbt_db_clickhouse
    image: clickhouse/clickhouse-server
    ports:
     - "8123"
     - "9004"
    volumes:
     - db_ch:/var/lib/clickhouse
    environment:
      CLICKHOUSE_DB: "${RBT_CLICKHOUSE_DB}"
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
      CLICKHOUSE_USER: "${RBT_CLICKHOUSE_USER}"
      CLICKHOUSE_PASSWORD: "${RBT_CLICKHOUSE_PASSWORD}"
    networks:
      rbt-app-network:
        ipv4_address: "${RBT_CLICKHOUSE_NETWORK_ADDRESS}"

  asterisk:
    container_name: rbt_asterisk
    build:
      context: .
      dockerfile: _docker/asterisk/Dockerfile
    volumes:
      - ./rbt/asterisk:/etc/asterisk
    depends_on:
      - nginx
    network_mode: host
    ## SIP UDP port 5060
    ## SIP TCP port 5060
    ## WS port 8088
    ## RTP ports 10000-20000

volumes:
  db:
  db_ch:
  mongodata:

networks:
  rbt-app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${RBT_NETWORK_ADDRESS}"
          gateway: "${RBT_NETWORK_GW}"