version: '3.8'

services:
  ## RBT intercom syslog
  rbt_syslog:
    container_name: rbt_syslog
    build: 
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./rbt/server/syslog:/home/node/app
    ports:
      - "${RBT_SYSLOG_PORT_BEWARD}:${RBT_SYSLOG_PORT_BEWARD}/udp" 
      - "${RBT_SYSLOG_PORT_BEWARD_DS}:${RBT_SYSLOG_PORT_BEWARD_DS}/udp" 
      - "${RBT_SYSLOG_PORT_QTECH}:${RBT_SYSLOG_PORT_QTECH}/udp"
      - "${RBT_SYSLOG_PORT_IS}:${RBT_SYSLOG_PORT_IS}/udp"
      - "${RBT_SYSLOG_PORT_AKUVOX}:${RBT_SYSLOG_PORT_AKUVOX}/udp"   
    command: npm run start