FROM debian:buster-slim

LABEL maintainer="LanTa team"

USER root

# Set environment
ENV ASTERISK_VERSION=18-current \
    LUA_VERSION=5.4.4 \
    LUAROCKS_VERSION=3.9.1
# Set build deps
ENV BUILD_DEPS \
    g++ \
    gcc \
    libc-dev \
    libreadline-dev \
    make \
    unzip \
    wget \
    curl \
    git \
    libcurl4-openssl-dev \
    libssl-dev

RUN set -xe && \
        apt-get update -y && apt-get install -y --no-install-recommends --no-install-suggests \
            ${BUILD_DEPS} \
            # Persistent Deps
            ca-certificates \
            libncurses6 \
            libreadline7
#         && \
#        # Install Lua
#        wget http://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz && \
#        tar zxf lua-${LUA_VERSION}.tar.gz && rm -f lua-${LUA_VERSION}.tar.gz && \
#        cd lua-${LUA_VERSION} && \
#        make -j $(getconf _NPROCESSORS_ONLN) linux && make install && \
#        cd / && rm -rf lua-${LUA_VERSION} && \
#        # Install LuaRocks
#        wget https://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz && \
#        tar zxf luarocks-${LUAROCKS_VERSION}.tar.gz && rm -f luarocks-${LUAROCKS_VERSION}.tar.gz && \
#        cd luarocks-${LUAROCKS_VERSION} && \
#        ./configure && \
#        make -j $(getconf _NPROCESSORS_ONLN) build && make install && \
#        cd / && rm -rf luarocks-${LUAROCKS_VERSION} && \
#        # Test
#        lua -v && luarocks

#RUN set -xe && \
#    ### Install Lua
#    wget http://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz && \
#    tar zxf lua-${LUA_VERSION}.tar.gz && rm -f lua-${LUA_VERSION}.tar.gz && \
#    cd lua-${LUA_VERSION} && \
#    make -j $(getconf _NPROCESSORS_ONLN) linux && make install && \
#    cd / && rm -rf lua-${LUA_VERSION}
    # Install LuaRocks
#    wget https://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz && \
#    tar zxf luarocks-${LUAROCKS_VERSION}.tar.gz && rm -f luarocks-${LUAROCKS_VERSION}.tar.gz && \
#    cd luarocks-${LUAROCKS_VERSION} && \
#    ./configure && \
#    make -j $(getconf _NPROCESSORS_ONLN) build && make install && \
#    cd / && rm -rf luarocks-${LUAROCKS_VERSION} && \
#    ### Test
#    lua -v && luarocks --version


### Install rocks
#RUN luarocks install luasocket 3.1.0 && \
#    luarocks install luasec 1.2.0 && \
#    luarocks install inspect 3.0 && \
#    luarocks install lua-cjson 2.1.0-1 && \
#    luarocks install redis-lua 2.0.4 && \
#     # Test
#    lua -v && luarocks

#WORKDIR /
COPY ./_docker/asterisk/build-asterisk.sh /


RUN sh build-asterisk.sh

RUN set -xe && \
    ### Install Lua
    wget http://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz && \
    tar zxf lua-${LUA_VERSION}.tar.gz && rm -f lua-${LUA_VERSION}.tar.gz && \
    cd lua-${LUA_VERSION} && \
    make -j $(getconf _NPROCESSORS_ONLN) linux && make install && \
    cd / && rm -rf lua-${LUA_VERSION} && \
    ### Install LuaRocks
    wget https://luarocks.org/releases/luarocks-${LUAROCKS_VERSION}.tar.gz && \
    tar zxf luarocks-${LUAROCKS_VERSION}.tar.gz && rm -f luarocks-${LUAROCKS_VERSION}.tar.gz && \
    cd luarocks-${LUAROCKS_VERSION} && \
    ./configure && \
    make -j $(getconf _NPROCESSORS_ONLN) build && make install && \
    cd / && rm -rf luarocks-${LUAROCKS_VERSION} && \
    ### Test
    lua -v && luarocks --version


## Install rocks
RUN luarocks install luasocket 3.1.0 && \
    luarocks install luasec 1.2.0 && \
    luarocks install inspect 3.0 && \
    luarocks install lua-cjson 2.1.0-1 && \
    luarocks install redis-lua 2.0.4 && \
     # Test
    lua -v && luarocks

EXPOSE 5060/udp 5060/tcp 8088/tcp 10000:20000/udp

COPY ./_docker/asterisk/docker-entrypoint.sh /

WORKDIR /

RUN chmod +x /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]

# CMD ["/usr/sbin/asterisk", "-vvvdddf", "-T", "-W", "-U", "asterisk", "-p"]
# CMD ["/usr/sbin/asterisk", "-mqf", "-C", "/etc/asterisk/asterisk.conf", "-U", "root"]
CMD ["/usr/sbin/asterisk", "-vvvvvvc", "-U", "root"]

